name: Purge camo links to update badge test status
on:
  workflow_dispatch:
  schedule:
    - cron: '0 30 * * *'
    - cron: '12 30 * * *'

jobs:
  camo-purge:
    runs-on: ubuntu-latest
    steps:
    - uses: kevincobain2000/action-camo-purge@v1
            
