name: Purge camo links to update badge test status
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'
    - cron: '30 12 * * *'

jobs:
  camo-purge:
    runs-on: ubuntu-latest
    steps:
      - uses: kevincobain2000/action-camo-purge@v1
            
